# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1be876899aa950f5154d5e9c350ff22fdebe4af0575a61cca095a5ed1eaa08f53898ce6230f255183a4ecaf1f5369bcad670d737b8e9d02170c1a15fa08af8e1

test:
  secret_key_base: e31390b07022522fc585c38d93ef7e6b0427763fda3214865a0042d4b113b4233c6e16503d80557772641a0c25d5b164c5c24f6346b272928e230fa6fad1a2a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
